# 设置自动按键
# 支持字母键如 "Q", "E"，数字键如 "1", "2"，功能键如 "F1", "F2" 等
# 如果不需要的按键，使用#注释掉即可
select: "Q"                 # 自动选怪
attack: "E"                 # 自动攻击
# ride_horse: "F10"           # 骑马键
# dingweifu: "F9"             # 定位符键
# emei_qinxin: "F8"           # 峨眉清心